#!/usr/bin/env bash
# Source inventory (#75) — the ONE honest answer to "what source should checkup
# assess?", so the tool never mistakes "we didn't look" for "nothing's there".
#
# Instead of guessing roots from a hard-coded `src server` convention (which
# silently scoped out code kept under scripts/, prisma/, packages/, …), the scope
# is enumerated from the project's OWN notion of source — the VCS — and is
# `.gitignore`-aware for free, so generated/vendored junk (a `.vercel/` build
# output, a committed bundle) doesn't pollute the localiser. Three tiers, honest
# fallback:
#   1. git repo   → `git ls-files` (tracked files; respects .gitignore inherently)
#   2. non-git+fd → `fd` (respects .gitignore/.ignore) — used only if present
#   3. non-git    → `find` with the builtin excludes (a legacy tree has no
#                   .gitignore to honour anyway)
#
# The result is a single NUL-delimited file list ($RAW_DIR/source-files.lst) plus
# a count and a scope label. Scanners that don't honour .gitignore (lizard) are
# fed this list directly; scanners that traverse themselves (eslint, scc) keep
# their own invocation and their findings are filtered back to this list, so the
# inventory is the single authority for "what counts".
#
# Sourced (not executed) — needs GIT_OK / TARGET / SCAN_ROOTS / RAW_DIR from the
# orchestrator. The pure filter (_filter_inventory) takes its input on stdin so
# it is unit-testable with no git/fd/find present (mirrors lib/detect-stacks.jq's
# "one shared transform, env-independent test" pattern).

# Extensions checkup measures per-function / per-file (lizard-parseable plus the
# JS/TS module variants). Anchored at end-of-path; used by the pure filter and by
# inventory_paths. Keep in sync with the probe sets in bin/checkup.sh.
SOURCE_EXT_RE='\.(ts|tsx|js|jsx|mjs|cjs|svelte|vue|py|cs|java|kt|kts|go|rb|php|rs|c|cc|cpp|cxx|h|hpp|m|mm|swift|scala|lua)$'

# Sub-slices, so each scanner gets exactly the files it can parse:
INV_JSTS_RE='\.(ts|tsx|js|jsx|mjs|cjs|svelte|vue)$'                                           # ESLint / Node engines
INV_NONJS_RE='\.(py|cs|java|kt|kts|go|rb|php|rs|c|cc|cpp|cxx|h|hpp|m|mm|swift|scala|lua)$'      # lizard's non-JS slice (#68)
INV_LIZARD_RE='\.(ts|tsx|js|jsx|py|cs|java|kt|kts|go|rb|php|rs|c|cc|cpp|cxx|h|hpp|m|mm|swift|scala|lua)$'  # everything lizard tokenises

# Generated-file markers (#114, plan 0002 Phase 2). BANNER-SHAPED + case-sensitive,
# NOT loose substrings: the spike's `@generated|DO NOT EDIT|…` (case-insensitive)
# fired on first-party code that merely *mentions* a marker (codegen tooling,
# Flow/Relay, lint configs) or owns it (IaC `# DO NOT EDIT`, hand-written
# migrations) — Morlock M1. Three anchored forms, matched as whole comment lines:
#   1. Go canonical:   `// Code generated <by …>. DO NOT EDIT.`  (full line)
#   2. `@generated`:    only inside a comment leader at line start (//, #, *, /*, --, <!--)
#   3. C# designer:     `<auto-generated>` at line start (optionally `// `-prefixed)
# Bare `DO NOT EDIT` is deliberately NOT a marker (too weak; it owns IaC/migrations).
INV_GENERATED_RE='^//[[:space:]]*Code generated .* DO NOT EDIT\.[[:space:]]*$|^[[:space:]]*(//|#|\*|/\*|--|<!--)[[:space:]]*@generated([[:space:]]|\(|$)|^[[:space:]]*(//[[:space:]]*)?<auto-generated'

# Should this path be excluded as tracked-but-noisy? `.gitignore` already drops
# generated/ignored output; this catches the COMMITTED noise it doesn't —
# vendored trees, minified bundles, migrations, snapshots — that would otherwise
# dominate the complexity/duplication signal. Mirrors the prior LIZARD_EXCLUDES
# globs; CHECKUP_EXCLUDE adds more (space-separated), same as before.
_inventory_excluded() {
    local p="$1" g
    # Directory excludes: match against "/$p" so a LEADING segment (top-level
    # node_modules/, dist/) is caught the same as a nested one (*/node_modules/*).
    case "/$p" in
        */node_modules/*|*/dist/*|*/build/*|*/.svelte-kit/*|\
        */vendor/*|*/vendored/*|*/third_party/*|\
        */migrations/*|*/__snapshots__/*|*/snapshots/*) return 0 ;;
    esac
    # File-suffix excludes (committed minified/generated/snapshot files).
    case "$p" in *.min.js|*.min.css|*.bundle.js|*.snap) return 0 ;; esac
    if [ -n "${CHECKUP_EXCLUDE:-}" ]; then
        # Split CHECKUP_EXCLUDE into globs WITH pathname expansion disabled: the
        # caller's cwd is the scan target, so an unguarded `for g in $CHECKUP_EXCLUDE`
        # would glob a directory pattern like `vendor/js/*` against the filesystem
        # (expanding it to its literal children, which then never match a nested
        # path) — the reason directory excludes silently did nothing (#109/#18).
        # `set -f` stops that; the `case` pattern below is matched as a glob anyway.
        local g _had_noglob; case $- in *f*) _had_noglob=1 ;; *) _had_noglob=0 ;; esac
        set -f
        # shellcheck disable=SC2086  # intentional word-split into glob patterns
        for g in $CHECKUP_EXCLUDE; do
            # shellcheck disable=SC2254  # $g is an intentional glob pattern
            case "$p" in $g) [ "$_had_noglob" = 0 ] && set +f; return 0 ;; esac
        done
        [ "$_had_noglob" = 0 ] && set +f
    fi
    return 1
}

# Pure filter: NUL-delimited candidate paths on stdin → NUL-delimited source
# paths on stdout (source extension AND not excluded). No git/fd/find needed, so
# the test can inject a synthetic list. NUL throughout so paths with spaces or
# newlines survive.
_filter_inventory() {
    local p
    while IFS= read -r -d '' p; do
        p="${p#./}"   # normalise the find/fd "./" prefix → one TARGET-relative namespace
        [[ "$p" =~ $SOURCE_EXT_RE ]] || continue
        _inventory_excluded "$p" && continue
        printf '%s\0' "$p"
    done
}

# Resolve the scan roots. Default is the whole tree (".") — honest by default.
# CHECKUP_SRC_ROOTS NARROWS it (focus, or perf on a huge monorepo): space-
# separated, filtered to roots that actually exist; if none exist, fall back to
# the whole tree rather than scanning nothing.
resolve_scan_roots() {
    SCAN_ROOTS=()
    if [ -n "${CHECKUP_SRC_ROOTS:-}" ]; then
        local r
        # shellcheck disable=SC2206  # intentional word-split of the override list
        local requested=(${CHECKUP_SRC_ROOTS})
        for r in "${requested[@]}"; do [ -d "$r" ] && SCAN_ROOTS+=("$r"); done
    fi
    [ "${#SCAN_ROOTS[@]}" -eq 0 ] && SCAN_ROOTS=(".")
    return 0   # never let a false final test trip `set -e` in the caller
}

# Build the inventory. Writes $RAW_DIR/source-files.lst (NUL-delimited), sets
# SOURCE_FILE_COUNT, SOURCE_SCOPE, SOURCE_LST. Run AFTER resolve_scan_roots and
# with cwd == TARGET (so paths are TARGET-relative, sharing the namespace the
# file scanners + git-forensics use).
build_source_inventory() {
    local lst="$RAW_DIR/source-files.lst"
    mkdir -p "$RAW_DIR"
    if [ "${GIT_OK:-false}" = true ]; then
        SOURCE_SCOPE="git"
        git ls-files -z -- "${SCAN_ROOTS[@]}" 2>/dev/null | _filter_inventory > "$lst"
    elif command -v fd > /dev/null 2>&1; then
        SOURCE_SCOPE="fd"
        fd --type f --hidden --no-follow --print0 . "${SCAN_ROOTS[@]}" 2>/dev/null | _filter_inventory > "$lst"
    else
        SOURCE_SCOPE="find"
        find "${SCAN_ROOTS[@]}" \( -name node_modules -o -name .git \) -prune -o \
            -type f -print0 2>/dev/null | _filter_inventory > "$lst"
    fi
    _apply_gitattr_excludes "$lst"          # author-declared generated/vendored (.gitattributes)
    _apply_generated_excludes "$lst"        # generated-file markers (#114, opt-in CHECKUP_EXCLUDE_GENERATED)
    [ -n "${CHECKUP_SRC_ROOTS:-}" ] && SOURCE_SCOPE="override:$SOURCE_SCOPE"
    SOURCE_LST="$lst"
    SOURCE_FILE_COUNT=$(tr -cd '\0' < "$lst" | wc -c | tr -d ' ')
}

# Like _filter_inventory, but WITHOUT the source-extension allow-list — only the
# provenance/convention/CHECKUP_EXCLUDE exclusion. This is the keep-set for the
# scc-based engines (stats/identity/tech-viability), which count ALL languages —
# first-party JSON/Markdown/config too, not just the SOURCE_EXT_RE slice that
# lizard/ESLint measure per-function. Same normalisation + exclusion as the source
# filter, so the two share one namespace and one notion of "excluded".
_filter_keep() {
    local p
    while IFS= read -r -d '' p; do
        p="${p#./}"
        _inventory_excluded "$p" && continue
        printf '%s\0' "$p"
    done
}

# Drop paths the repo's author declared generated/vendored via `.gitattributes`
# (linguist-generated / linguist-vendored) — the highest-confidence, no-regex
# exclusion (#109 Phase 1). Let git parse the attributes (git check-attr), never a
# hand-rolled parser. git-only and a no-op without a .gitattributes; rewrites the
# NUL list at $1 in place, preserving order. `check-attr -z` streams triplets
# (path NUL attr NUL value NUL); a path is excluded when either attr is "set" or
# "true" ("false"/"unspecified" keep it).
_apply_gitattr_excludes() {
    local lst="$1"
    [ "${GIT_OK:-false}" = true ] && [ -s "$lst" ] || return 0
    # Skip the check-attr pass entirely when no .gitattributes is tracked — it would
    # otherwise stream an "unspecified" triplet per file for nothing on big trees.
    [ -n "$(git ls-files -z -- '.gitattributes' '*/.gitattributes' 2>/dev/null | head -c1)" ] || return 0
    local p a v
    declare -A _flagged=()
    while IFS= read -r -d '' p && IFS= read -r -d '' a && IFS= read -r -d '' v; do
        case "$v" in set|true) _flagged["$p"]=1 ;; esac
    done < <(git check-attr -z --stdin linguist-generated linguist-vendored < "$lst" 2>/dev/null)
    GITATTR_EXCLUDED_COUNT="${#_flagged[@]}"   # author-declared (coverage signal, #117)
    [ "${#_flagged[@]}" -eq 0 ] && return 0
    local out="$lst.attr"
    while IFS= read -r -d '' p; do
        [ -n "${_flagged[$p]:-}" ] || printf '%s\0' "$p"
    done < "$lst" > "$out"
    mv "$out" "$lst"
    return 0
}

# Drop files whose head carries a BANNER-SHAPED generated marker (#114, plan 0002
# Phase 2) — the corvus lever. DEFAULT-ON since Phase 3 (#117): the markers are
# field-proven and the shrink is announced by a loud banner, so excluding generated
# code is the honest default. KILL-SWITCH: `CHECKUP_EXCLUDE_GENERATED=0` (also
# false/no/off) restores the whole tree. Rewrites the NUL list at $1 in place
# (order-preserving) and ENUMERATES the dropped files to "<lst>.generated" (loud,
# not a silent count — the guard that earns the subtractive design; over-exclusion
# is the danger). Sets GENERATED_EXCLUDED_COUNT. Runs with cwd == TARGET so the
# relative paths open.
_apply_generated_excludes() {
    local lst="$1"
    case "${CHECKUP_EXCLUDE_GENERATED:-1}" in 0|false|no|off) return 0 ;; esac
    [ -s "$lst" ] || return 0
    local flagged="$lst.generated"
    # grep -l short-circuits on the first match per file (the marker is at the head),
    # so even a mostly-generated tree is cheap; -I skips binaries; LC_ALL=C makes the
    # match byte-deterministic (#96). xargs streams the list (ARG_MAX-safe, #105).
    LC_ALL=C xargs -0 grep -lIZ -E "$INV_GENERATED_RE" < "$lst" 2>/dev/null > "$flagged" || true
    if [ ! -s "$flagged" ]; then rm -f "$flagged"; return 0; fi
    local p out="$lst.gen"
    declare -A _gen=()
    while IFS= read -r -d '' p; do _gen["$p"]=1; done < "$flagged"
    while IFS= read -r -d '' p; do
        [ -n "${_gen[$p]:-}" ] || printf '%s\0' "$p"
    done < "$lst" > "$out"
    mv "$out" "$lst"
    GENERATED_EXCLUDED_COUNT="${#_gen[@]}"
    return 0
}

# Build the scc keep-set: VCS-tracked files (ALL extensions) minus the exclusions,
# as a JSON array at $RAW_DIR/scc-keep.json (sets SCC_KEEP_JSON). The scc-based
# engines filter their --by-file output against this (lib/scc-inventory.sh), so
# stats/identity reflect first-party code, not the whole tree (#109). Same tiers
# as build_source_inventory; run AFTER resolve_scan_roots, cwd == TARGET.
#
# Subtraction is STAGED so the coverage signal (#117 Phase 3) can attribute every
# excluded file to a category — convention (builtin globs + CHECKUP_EXCLUDE),
# author-declared (.gitattributes), generated (markers) — computed from the count
# delta at each stage (robust to the helpers' internals). Sets, over the ALL-
# extension candidate set: SCC_CANDIDATE_COUNT (everything tracked), SCC_KEEP_COUNT
# (kept), CONVENTION_EXCLUDED_COUNT, GITATTR_EXCLUDED_COUNT, GENERATED_EXCLUDED_COUNT.
build_scc_keepset() {
    local lst="$RAW_DIR/scc-keep.lst" raw="$RAW_DIR/scc-keep.raw"
    SCC_KEEP_JSON="$RAW_DIR/scc-keep.json"
    mkdir -p "$RAW_DIR"
    # Enumerate ALL tracked candidates first (every extension), so each subtraction
    # stage below has an honest denominator.
    if [ "${GIT_OK:-false}" = true ]; then
        git ls-files -z -- "${SCAN_ROOTS[@]}" 2>/dev/null > "$raw"
    elif command -v fd > /dev/null 2>&1; then
        fd --type f --hidden --no-follow --print0 . "${SCAN_ROOTS[@]}" 2>/dev/null > "$raw"
    else
        find "${SCAN_ROOTS[@]}" \( -name node_modules -o -name .git \) -prune -o \
            -type f -print0 2>/dev/null > "$raw"
    fi
    SCC_CANDIDATE_COUNT=$(tr -cd '\0' < "$raw" | wc -c | tr -d ' ')
    _filter_keep < "$raw" > "$lst"          # convention globs + CHECKUP_EXCLUDE
    rm -f "$raw"
    local after_conv; after_conv=$(tr -cd '\0' < "$lst" | wc -c | tr -d ' ')
    CONVENTION_EXCLUDED_COUNT=$(( SCC_CANDIDATE_COUNT - after_conv ))
    _apply_gitattr_excludes "$lst"          # author-declared generated/vendored (.gitattributes)
    local after_attr; after_attr=$(tr -cd '\0' < "$lst" | wc -c | tr -d ' ')
    GITATTR_EXCLUDED_COUNT=$(( after_conv - after_attr ))
    _apply_generated_excludes "$lst"        # generated-file markers (#114, default-on; CHECKUP_EXCLUDE_GENERATED=0 disables)
    SCC_KEEP_COUNT=$(tr -cd '\0' < "$lst" | wc -c | tr -d ' ')
    GENERATED_EXCLUDED_COUNT=$(( after_attr - SCC_KEEP_COUNT ))
    jq -Rs 'split("\u0000") | map(select(length > 0))' < "$lst" > "$SCC_KEEP_JSON" 2>/dev/null \
        || printf '[]' > "$SCC_KEEP_JSON"
    return 0
}

# Emit (NUL-delimited) the inventory paths whose extension matches $1 (an ERE
# alternation anchored by the caller, e.g. "$INV_NONJS_RE"). Empty $1 → all.
# Consume with: mapfile -d '' ARR < <(inventory_paths "$INV_NONJS_RE")
inventory_paths() {
    local re="${1:-}" p
    [ -f "${SOURCE_LST:-}" ] || return 0
    while IFS= read -r -d '' p; do
        [ -z "$re" ] || [[ "$p" =~ $re ]] || continue
        printf '%s\0' "$p"
    done < "$SOURCE_LST"
}

# The inventory as a JSON array of paths — for filtering a scanner's findings
# back to the tracked set (e.g. ESLint, which traverses on its own).
inventory_json() {
    inventory_paths "${1:-}" | jq -Rs 'split("\u0000") | map(select(length > 0))'
}

# The inventory grouped by top-level directory -> JSON object {area: count}, for
# the coverage signal (#75). Root-level files roll up under "<root>". NUL list is
# converted to newlines first (paths with embedded newlines are vanishingly rare
# and only affect this display grouping, never measurement).
inventory_by_area_json() {
    inventory_paths "" | tr '\0' '\n' | jq -R -s '
        split("\n") | map(select(length > 0))
        | group_by(if contains("/") then split("/")[0] else "<root>" end)
        | map({ key: (.[0] | if contains("/") then split("/")[0] else "<root>" end),
                value: length })
        | from_entries'
}

# Where the inventory got its exclusions from, for honest reporting. git/fd
# honour the repo's .gitignore; the find fallback only has checkup's builtin
# vendored/generated globs.
inventory_exclusion_source() {
    case "${SOURCE_SCOPE:-}" in
        *git)  echo ".gitignore" ;;
        *fd)   echo ".gitignore + .ignore" ;;
        *)     echo "builtin excludes (no VCS)" ;;
    esac
}

# Resolve an ESLint flat config at <dir> (default "."). Prints the first
# eslint.config.{js,mjs,cjs,ts}, or nothing + rc 1. This is the ONLY place
# `eslint .` from the root resolves a flat config (ESLint v9 does not search
# upward for the root invocation), so it gates the ESLint complexity slice (#79)
# — and #73 reuses it for the non-node-dominant case. Pure: a file test, no eslint
# needed, so it's unit-testable.
eslint_flat_config_root() {
    local dir="${1:-.}" c
    for c in eslint.config.js eslint.config.mjs eslint.config.cjs eslint.config.ts; do
        [ -f "$dir/$c" ] && { printf '%s' "$dir/$c"; return 0; }
    done
    return 1
}
